defaults:
  - model: small
  - vocab: yelp
  - dataset: yelp
  - optimizer: adamw
  - scheduler: cosine
  - _self_

epochs: 3
batch_size: 1536
accumulation_steps: 24

checkpoint_interval: 5000
log_interval: 100
