defaults:
  - model: tiny
  - vocab: yelp
  - dataset: yelp
  - optimizer: adamw
  - scheduler: cosine
  - _self_

epochs: 1
batch_size: 1536
accumulation_steps: 48

checkpoint_interval: 5000
log_interval: 100
